### ISSUE TITLE
Bump requests to 2.31.0

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-proxy#118]
A requests bug was found: [GHSA-j8r2-6x86-q33q](https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q)

We're not directly affected AFAICT but bumping the version is no harm.

Diff review done in https://github.com/freedomofpress/securedrop/issues/6820

**Comment by rocodes** [comment]
(Note that https://github.com/freedomofpress/securedrop-builder/pull/454 will need review as well before https://github.com/freedomofpress/securedrop-proxy/pull/119 will pass CI; commenting here for visibility since we're tracking issues not PRs in the dev board)
