### ISSUE TITLE
Switch this package to poetry for Python dependency management

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-proxy#123]
- [x] Add support for Poetry in `securedrop-builder` - https://github.com/freedomofpress/securedrop-builder/pull/467
- [x] Update `build-requirements.txt` path in a backwards-compatible manner https://github.com/freedomofpress/securedrop-builder/pull/469
- [x] Re-run CI on #122 and ensure expected checks are green (PyYAML errors on Bookworm are expected, see #121)
- [x] Review and merge #122
- [x] Re-run CI on https://github.com/freedomofpress/securedrop-builder/pull/470 and ensure expected checks are green
- [x] Review and merge https://github.com/freedomofpress/securedrop-builder/pull/470

**Comment by eloquence** [comment]
@legoktm Proposed order of operations for switching proxy over :)

**Comment by legoktm** [comment]
All done \o/
