### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-proxy#9]
This project is missing a LICENSE file. This is required for the packaging/setup.py work

**Comment by kushaldas** [comment]
@redshiftzero @joshuathayer If you are okay then I can submit a PR with a GPLv3+ license.

**Comment by redshiftzero** [comment]
yep! feel free to submit a PR adding a GPLv3 license

**Comment by redshiftzero** [comment]
closed by #10
